### PR TITLE
require `revealCurve` to increses curve limit

### PR DESCRIPTION
**Pull request by sophiii**
required `revealCurve` to have a limit grater than previous curve

### CODE REVIEW

**Comment by nfnty** [comment]
It's impossible to reveal the same curve twice. You can only reveal the curve that comes after the last one revealed. That if-statement is just for extra safety in case the committed curves were in some way faulty. Committing 2 curves with the same limit may seem weird, but it doesn't violate any logic.

**Comment by nfnty** [comment]
It's impossible to reveal the same curve twice. You can only reveal the curve that comes after the last one revealed. That if-statement is just for extra safety in case the committed curves were in some way faulty. Committing 2 curves with the same limit may seem weird, but it doesn't violate any logic.

**Comment by sophiii** [comment]
@jarradh we should remove the ability to do weird things with the curves. This functionality should be constrained. The next `limit` should be greater than the last. There is no point having the next curve with the same limit as the last one.

**Comment by nfnty** [comment]
Having a new curve with the same limit could have benefits depending on how the previous curves are tuned. In case `moveTo()` has to be called the new curve could have different parameters, affecting how the crowdsale progresses. Otherwise nothing special happens, the curve will just be skipped.

**Pull request closed without merging**
