### PR TITLE
contracts: StatusContribution: Block contracts from `buyNormal`

### PR DESCRIPTION
**Pull request by nfnty**

### CODE REVIEW

**Comment by MicahZoltu** [comment]
Same comment as https://github.com/status-im/status-network-token/pull/121#issuecomment-309079043, I really think this is a bad idea (disallows investment by multi-sig wallets or other smart wallets).  Would like to see more open discussion about the attack vectors this protects against.  The naive vectors that it seems to be protecting against I don't believe it actually protects, instead it just changes the vector a little bit and/or marginally increases gas costs.

Unless the _goal_ is to make it so that no one using a smart wallet (i.e., an increased security wallet) can participate, then I think this should not be merged.

**Comment by nfnty** [comment]
@izqui Posted this snippet earlier that convinced me:
```
contract Spammer {
  StatusContribution constant statusSale = StatusContribution(0);

  function () payable {
    for (uint i = 0; i < 20 && this.balance > 0; i++) {
      statusSale.proxyPayment.value(this.balance)(msg.sender);
    }
  }
}
```

Someone could buy multiple times in one TX with this contract, defeating the dynamic ceilings completely. We've discussed alternatives and whitelisting is currently the best solution, but we haven't decided yet to implement it.

**Comment by MicahZoltu** [comment]
I can write that same loop _outside_ of a contract (e.g., in Python) and have basically the same effect.  If I throw 20 transactions simultaneously into the pending transaction pool of my local node, all with the same gas price, it is _very_ likely they'll propagate together and end up one after the other in the miner's pending transaction queue.  While I don't get the strong guarantee that a contract provides, I get the same net effect, or at least a close enough proxy to that to suit a large buyer's needs.

With the anti-spam code I can do the same thing but have the 20 transactions all come from different accounts (different origins).  There is no way for your contract to tell this apart from 20 unique buyers so this is an unsolvable problem in the contracts.

The only caveat with the Python solution is that I have to spread my funds out across enough accounts so as to make it unlikely that any one of them will be individually capped.  With the cost of spreading out funds being less than a penny, the only costs of significance I'm eating are transaction costs for the actual buy.  As we have seen in previous ICOs though, transaction costs are all relative to buy-in size.  A whale has no problem eating 1% of their total buy-in on transaction costs, so if we assume that calling the buy contract is $0.50 (at the 50 nanoeth gas cap), then this means that the whale could spread out into accounts with $50 in each of them.  If they want to do a $1M buy-in, this means they are spread out over 20,000 accounts and your contract _can't_ (its impossibel) tell the difference between that and 20,000 non-whale buyers.

**Comment by nfnty** [comment]
With the smart contract only one TX has to confirm, whereas with the script you'd need them all (or a big part of them) to line up, which is close to impossible. The net effect is not even close to the same. We're trying to reduce attack surface, but it's never going to be perfect, since Sybil attack is an unsolved problem without a strong reputation system.

We're going to tune the curves to make it very unprofitable for a whale to do what you just described.

**Comment by MicahZoltu** [comment]
The "attacker" (legitimate buyer of large quantities) doesn't need to get all of the transactions in order, just mostly together.  If someone else sneaks in a transaction somewhere in the middle of his 20,000 transaction batch then /shrug.

> We're going to tune the curves to make it very unprofitable for a whale to do what you just described.

Can you give an _example_ of a curve that would make what I described unprofitable?  In the above, the whale is simply paying a 1% transaction fee on their investment to make their investment _appear_ to be that of 20,000 goldfish.  Anything you do to punish them _also_ punishes the goldfish.  If you set really small ceilings, then the first `n` get through and the rest fail, which means all of those goldfish eat transaction costs, just like the whale.  You _cannot_ tax the whale without taxing the goldfish.

**Comment by nfnty** [comment]
Indeed, I won't go into to much detail on what's planned since that defeats the purpose of the ceilings being hidden. But we know about that problem and are taking it into calculation. We'll explain more after the crowdsale has finished.

**Comment by MicahZoltu** [comment]
The statement, "Trust us, we have solved Sybil attacks and will tell you about it later." doesn't instill much confidence in the crowdsale.

I would be fine with that argument if you could do it without hamstringing multi-sig contracts, but at the moment you are introducing what I see as a major security issue (disallowing multi-sig buyers) on the _claim_ that it enables you to solve the Sybil attack problem.

Is it possible for you to share a hypothetical (not-real) example of how one _could_ setup ceilings to stop Sybil attacks?  I'm not looking to get an head-start view of the real caps, just trying to understand how you believe to have solved Sybil attacks (even partially) since you are sacrificing so much end-user security in exchange for it.

Perhaps the idea is simply that regular users don't secure their funds (e.g., don't use multi-sig accounts) so by disallowing multi-sig accounts you are dis-allowing whales (who would be very apprehensive about investing large amounts of capital via a singly controlled account)?

**Pull request closed without merging**
